# Generated by Django 5.2.3 on 2025-06-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ciclo',
            field=models.CharField(blank=True, default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre_completo',
            field=models.CharField(blank=True, default='N/A', max_length=150),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='carnet',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='carrera',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
