# Generated by Django 5.2.3 on 2025-06-24 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialNewtonRaphson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=255)),
                ('valor_inicial', models.FloatField()),
                ('tolerancia', models.FloatField()),
                ('iteraciones_maximas', models.IntegerField()),
                ('raiz_aproximada', models.FloatField(blank=True, null=True)),
                ('error_final', models.FloatField(blank=True, null=True)),
                ('total_iteraciones', models.IntegerField()),
                ('exito', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_newton', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
